INSERT INTO TODO (ID, DESCRIPTION, USERNAME, TARGET_DATE, DONE) VALUES
(10001, 'Jordan', 'Get AWS Certified', CURRENT_DATE(), false);

INSERT INTO TODO (ID, DESCRIPTION, USERNAME, TARGET_DATE, DONE) VALUES
(10002, 'Jordan', 'Take out trash', CURRENT_DATE(), false);

INSERT INTO TODO (ID, DESCRIPTION, USERNAME, TARGET_DATE, DONE) VALUES
(10003, 'Izzy', 'Teach those kids', CURRENT_DATE(), false);

INSERT INTO TODO (ID, DESCRIPTION, USERNAME, TARGET_DATE, DONE) VALUES
(10004, 'Izzy', 'Buy some groceries', CURRENT_DATE(), false);